# Generated by Django 4.0.3 on 2022-03-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('student_roll', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_detail',
            fields=[
                ('Student_id', models.AutoField(primary_key=True, serialize=False)),
                ('marks', models.IntegerField(default=0)),
                ('Parent_name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
